steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/harshmalviya2023/dataflow.git']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'compile', 'exec:java', '-Dexec.mainClass=com.impetus.dataflow.IngestionPipeline', '-Dexec.args=--runner=DataflowRunner --project=learning-313419 --stagingLocation=gs://dataset2023/temp/staging --templateLocation=gs://dataset2023/IngestionPipeline --region=us-central1']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'dataflow/conf/IngestionPipeline_metadata', 'gs://dataset2023/IngestionPipeline_metadata']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/learning-313419/dataflow', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/learning-313419/dataflow']
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['cp', 'dataflow/conf/IngestionPipeline_metadata', 'gs://dataset2023/IngestionPipeline_metadata']
# - name: 'gcr.io/cloud-builders/gsutil'
#   args: ['cp', 'gs://your-bucket/your-image-name', 'gs://your-bucket/your-image-name']
#   - name: 'gcr.io/cloud-builders/docker'    
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/identityresolver', '.']  
#   - name: 'gcr.io/cloud-builders/docker'    
#   args: ['push', 'gcr.io/$PROJECT_ID/identityresolver']
